services:
    symbb.core.forum.breadcrumb:
        twig.extension.symbb.core.forum.breadcrumb:
        class: SymBB\Core\ForumBundle\Twig\BreadcrumbExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension } 
            
    symbb.core.forum.topic.data:
        twig.extension.symbb.core.forum.topic.data:
        class: SymBB\Core\ForumBundle\Twig\TopicDataExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension } 
            
    symbb.core.forum.data:
        twig.extension.symbb.core.forum.data:
        class: SymBB\Core\ForumBundle\Twig\ForumDataExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension } 
            
    symbb.core.forum.managers.twig:
        twig.extension.symbb.core.forum.managers.twig:
        class: SymBB\Core\ForumBundle\Twig\ManagerExtension
        arguments: ['@symbb.core.post.manager', '@symbb.core.forum.manager']
        tags:
            - { name: twig.extension }

    symbb.core.forum.manager:
        parent:  symbb.core.abstract.manager
        class: SymBB\Core\ForumBundle\DependencyInjection\ForumManager
        arguments: ['@symbb.core.topic.flag', '@symbb.core.post.flag', '@symbb.core.config.manager']

    symbb.core.post.manager:
        parent:  symbb.core.abstract.manager
        class: SymBB\Core\ForumBundle\DependencyInjection\PostManager
        arguments: ['@symbb.core.post.flag', '@symbb.core.config.manager']

    symbb.core.topic.manager:
        parent:  symbb.core.abstract.manager
        class: SymBB\Core\ForumBundle\DependencyInjection\TopicManager
        arguments: ['@symbb.core.topic.flag', '@symbb.core.config.manager']

            
            
    symbb.core.abstract.flag:
        abstract: true
        arguments: ['@doctrine.orm.symbb_entity_manager', '@symbb.core.user.manager', "@symbb.core.access.manager", '@security.context', '@memcache.default']
        calls:
            - [setEnviroment, ['%kernel.environment%']]
        
    symbb.core.forum.flag:
        class: SymBB\Core\ForumBundle\DependencyInjection\ForumFlagHandler
        parent: symbb.core.abstract.flag
        
    symbb.core.topic.flag:
        class: SymBB\Core\ForumBundle\DependencyInjection\TopicFlagHandler
        parent: symbb.core.abstract.flag
        calls:
            - [setForumFlagHandler, ["@symbb.core.forum.flag"]]
            
    symbb.core.post.flag:
        class: SymBB\Core\ForumBundle\DependencyInjection\PostFlagHandler
        parent: symbb.core.abstract.flag
        calls:
            - [setForumFlagHandler, ["@symbb.core.forum.flag"]]
            
    symbb.core.forum.notify:
        class: SymBB\Core\ForumBundle\DependencyInjection\NotifyHandler
        arguments: ['@service_container']
            
    symbb.core.forum.config:
        class: SymBB\Core\ForumBundle\EventListener\ConfigListener
        tags:
            - { name: kernel.event_listener, event: symbb.config.configs, method: configs }

    symbb.core.forum.security.access.post_voter:
        class:      SymBB\Core\ForumBundle\Security\Authorization\PostVoter
        public:     false
        arguments: ['@symbb.core.access.manager']
        tags:
           - { name: security.voter }

    symbb.core.forum.security.access.topic_voter:
        class:      SymBB\Core\ForumBundle\Security\Authorization\TopicVoter
        public:     false
        arguments: ['@symbb.core.access.manager']
        tags:
           - { name: security.voter }

    symbb.core.forum.security.access.forum_voter:
        class:      SymBB\Core\ForumBundle\Security\Authorization\ForumVoter
        public:     false
        arguments: ['@symbb.core.access.manager']
        tags:
           - { name: security.voter }

    symbb.core.forum.listener.template:
        class: SymBB\Core\ForumBundle\EventListener\TemplateListener
        tags:
            - { name: kernel.event_listener, event: symbb.template.forum.javascripts, method: javascripts }