symbb_api_ucp_data:
    pattern:  /api/ucp/data
    defaults: { _controller: SymbbCoreUserBundle:FrontendApi:ucpData }

symbb_api_user_ucp_save:
    pattern:  /api/ucp/save
    defaults: { _controller: SymbbCoreUserBundle:FrontendApi:ucpSave }

symbb_api_userlist:
    pattern:  /api/userlist/{page}
    defaults: { _controller: SymbbCoreUserBundle:FrontendApi:userlist, page: 1 }

symbb_api_user_search:
    pattern:  /api/user/search
    defaults: { _controller: SymbbCoreUserBundle:FrontendApi:search }

symbb_api_user_data:
    pattern:  /api/user/data
    defaults: { _controller: SymbbCoreUserBundle:FrontendApi:data }

symbb_userlist:
    pattern:  /users/{page}
    defaults:
      _controller: SymbbCoreUserBundle:Frontend:userlist

symbb_user_profile:
    pattern:  /user/{id}/{username}
    defaults:
      _controller: SymbbCoreUserBundle:Frontend:view

symbb_user_ucp:
    pattern:  /ucp/
    defaults: { _controller: SymbbCoreUserBundle:Ucp:index }

symbb_user_ucp_notifications:
    pattern:  /ucp/notifications/{page}
    defaults: { _controller: SymbbCoreUserBundle:Ucp:notification, page: 1 }

symbb_user_ucp_notification_unsubscribe:
    pattern:  /ucp/notification/{id}/unsubscribe
    defaults: { _controller: SymbbCoreUserBundle:Ucp:notificationUnsubscribe }

fos_user_registration_confirmed:
    path: /login/ok
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: symbb_forum_index
        permanent: true

symbb_user_ucp_security:
    pattern:  /ucp/security
    defaults: { _controller: SymbbCoreUserBundle:Ucp:security }