symbb_user_userlist:
    pattern:  /userlist
    defaults: { _controller: SymBBCoreUserBundle:Info:userlist }
    
symbb_user_profile:
    pattern:  /user/{id}/{name}
    defaults: { _controller: SymBBCoreUserBundle:Info:profile }

symbb_ucp_angular_template:
    pattern:  /angular/template/ucp/{file}
    defaults: { _controller: SymBBCoreUserBundle:Angular:templateFile }

symbb_api_ucp_data:
    pattern:  /api/ucp/data
    defaults: { _controller: SymBBCoreUserBundle:FrontendApi:ucpData }

symbb_api_user_ucp_save:
    pattern:  /api/ucp/save
    defaults: { _controller: SymBBCoreUserBundle:FrontendApi:ucpSave }

symbb_api_userlist:
    pattern:  /api/userlist/{page}
    defaults: { _controller: SymBBCoreUserBundle:FrontendApi:userlist, page: 1 }

symbb_api_user_search:
    pattern:  /api/user/search
    defaults: { _controller: SymBBCoreUserBundle:FrontendApi:search }
    
    
    
    