JMSTranslationBundle_ui:
    resource: "@JMSTranslationBundle/Controller/"
    type:     annotation
    prefix:   /_trans

SymBBExtensionBundle_Extra:
    resource: .
    prefix: /
    type: extra
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix: /

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
    
_symbb_frontend_routings:
    resource: "@SymBBCoreSystemBundle/Resources/config/routing/frontend.yml"
    prefix: /

_symbb_template_default_frontend:
    resource: "@SymBBTemplateDefaultBundle/Resources/config/routing/frontend.yml"
    prefix: /

_symbb_acp_routings:
    resource: "@SymBBCoreSystemBundle/Resources/config/routing/acp.yml"
    prefix: /acp

_symbb_acp_routings:
    resource: "@SymBBCoreSystemBundle/Resources/config/routing/acp.yml"
    prefix: /acp

_symbb_index:
    pattern:  /
    defaults: { _controller: SymBBCoreForumBundle:Frontend:forum }