services:
    symbb.extension.shoutbox.listener.template:
        class: Symbb\Extension\ShoutboxBundle\EventListener\TemplateListener
        tags:
            - { name: kernel.event_listener, event: symbb.template.global.stylesheets, method: stylesheets }
            - { name: kernel.event_listener, event: symbb.template.forum.javascripts, method: javascripts }
            - { name: kernel.event_listener, event: symbb.template.forum.afterMenu, method: renderBox }
