services:        
    symbb.core.site.manager:
        class: SymBB\Core\SiteBundle\DependencyInjection\SiteManager
        arguments: ["@service_container"]

    symbb.core.site.twig.extension:
        class: SymBB\Core\SiteBundle\Twig\Extension
        arguments: ['@symbb.core.site.manager']
        tags:
            - { name: twig.extension }

    symbb.core.site.menu_builder:
        class: SymBB\Core\SiteBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@event_dispatcher"]

    symbb.core.site.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: symbb.core.site.menu_builder
        factory_method: createMainMenu
        arguments: ["@request", "@symbb.core.site.manager"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu