services:
    symbb.template.default.form:
        twig.extension.symbb.template.default.form:
        class: SymBB\Template\DefaultBundle\Twig\FormExtension
        tags:
            - { name: twig.extension } 
            
    symbb.listener.site.template.default:
        class: SymBB\Template\DefaultBundle\EventListener\SiteListener
        tags:
            - { name: kernel.event_listener, event: symbb.core.site.acp.template_choices, method: templateChoices }

    symbb.template.default.twig.extension.loader:
        class: Twig_Extension_StringLoader
        tags:
             - { name: 'twig.extension' }

