services:
    symbb.core.event.twig:
        twig.extension.symbb.core.event.twig:
        class: Symbb\Core\EventBundle\Twig\EventExtension
        arguments: ['@event_dispatcher']
        tags:
            - { name: twig.extension } 