doctrine:
    dbal:
      types:
        timestamp: Symbb\Core\SystemBundle\Doctrine\TimestampType
      default_connection: default
      connections:
        symbb:
            driver:   "%database_driver%"
            host:     "%database_host%"
            port:     "%database_port%"
            dbname:   "%database_name%"
            user:     "%database_user%"
            password: "%database_password%"
            charset:  UTF8
            mapping_types:
                enum: string
    orm:
        entity_managers:
            default:
                auto_mapping: false
                connection:   default
            symbb:
                auto_mapping: false
                connection:   symbb
                mappings:
                    SymbbCoreAdminBundle: ~