fos_user:
    db_driver: orm
    firewall_name: symbb
    user_class: Symbb\Core\UserBundle\Entity\User
    model_manager_name: symbb
    group:
        group_class: Symbb\Core\UserBundle\Entity\Group
    registration:
        form:
            type: symbb_fos_user_registration
        confirmation:
            enabled:    true
    from_email:
        address:        %system.email%
        sender_name:    %system.name%
    service:
        mailer: fos_user.mailer.default

simple_things_form_extra:
    recaptcha:
        private_key: %recaptcha.private_key%
        public_key:  %recaptcha.public_key%