lsw_memcache:
    pools:
        default:
            servers:
              - { dsn: localhost, port: 11211 }
            options:
                # important if we have more than one symbb installations!
                prefix_key: %secret%
        acl:
            servers:
              - { dsn: localhost, port: 11211 }
            options:
                # important if we have more than one symbb installations!
                prefix_key: acl_%secret%