lsw_memcache:
    session:
        pool: default
        options:
            # important if we have more than one symbb installations!
            prefix_key: %secret%
    pools:
        default:
            servers:
              - { host: localhost, tcp_port: 11211 }
        acl:
            servers:
              - { host: localhost, tcp_port: 11211 }