lsw_memcache:
    session:
        pool: default
        prefix: %secret%
    pools:
        default:
            servers:
              - { host: localhost, tcp_port: 11211 }
        acl:
            servers:
              - { host: localhost, tcp_port: 11211 }