knp_gaufrette:
    stream_wrapper: ~

    adapters:
        symbb_adapter:
            local:
                directory: %kernel.root_dir%/../web/symbb/images/forum
        symbb_post_file_adapter:
            local:
                directory: %kernel.root_dir%/../web/symbb/files/post

    filesystems:
        symbb_forum_image_fs:
            adapter:    symbb_adapter
        symbb_post_files_fs:
            adapter:    symbb_post_file_adapter