services:
    symbb.listener.post.survey.template:
        class: Symbb\Extension\SurveyBundle\EventListener\TemplateListener
        arguments: ['@doctrine.orm.symbb_entity_manager']
        tags:
            - { name: kernel.event_listener, event: symbb.core.forum.post.template.form.options.tabs, method: addPostTab }
            - { name: kernel.event_listener, event: symbb.core.forum.post.template.form.options.tabcontents, method: addPostTabContent }
            - { name: kernel.event_listener, event: symbb.core.forum.topic.template.form.options.tabs, method: addTopicTab }
            - { name: kernel.event_listener, event: symbb.core.forum.topic.template.form.options.tabcontents, method: addTopicTabContent }
            - { name: kernel.event_listener, event: symbb.core.forum.post.template.before.text, method: addSurveyBlock }
            - { name: kernel.event_listener, event: symbb.template.global.stylesheets, method: stylesheets }

    symbb.extension.survey.listener.post.form:
        class: Symbb\Extension\SurveyBundle\EventListener\FormListener
        arguments: ['@symbb.core.user.manager', '@doctrine.orm.symbb_entity_manager']
        tags:
            - { name: kernel.event_listener, event: symbb.core.forum.topic.post.create, method: postForm }

    symbb.listener.post.survey.save:
        class: Symbb\Extension\SurveyBundle\EventListener\SaveListener
        arguments: ['@doctrine.orm.symbb_entity_manager', '@symbb.core.user.manager']
        tags:
            - { name: kernel.event_listener, event: symbb.core.forum.form.post.after.save, method: savePost }
            - { name: kernel.event_listener, event: symbb.core.forum.form.topic.after.save, method: saveTopic }
            
    symbb.listener.topic.labels:
        class: Symbb\Extension\SurveyBundle\EventListener\TopicLabelListener
        arguments: ['@doctrine.orm.symbb_entity_manager']
        tags:
            - { name: kernel.event_listener, event: symbb.topic.labels, method: topicLabels }


    symbb.extension.survey.security.access.survey_voter:
        class:      Symbb\Extension\SurveyBundle\Security\Authorization\SurveyVoter
        public:     false
        arguments: ['@symbb.core.access.manager']
        tags:
           - { name: security.voter }
            
            
            