# AngularJs Controller Routings
# This will create a SF Controller AND a AngularJs Controller automaticly
# and provide the correct content

## FORUM BUNDLE

symbb_forum_post_create:
    pattern:  /t-{topic}/post/new
    defaults: { _controller: SymbbCoreAngularBundle:Angular:index }
    options:
      symbb_angular_controller: ForumPostEditCtrl
      symbb_angular_api_route: symbb_api_post_data
      symbb_angular_template:
          route: symbb_template_forum_angular
          params:
              file: 'post'

symbb_forum_post_quote:
    pattern:  /p-{topic}/quote/{quoteId}
    defaults: { _controller: SymbbCoreAngularBundle:Angular:index }
    options:
      symbb_angular_controller: ForumPostEditCtrl
      symbb_angular_api_route: symbb_api_post_data
      symbb_angular_template:
          route: symbb_template_forum_angular
          params:
              file: 'post'


## MESSAGE BUNDLE

symbb_message_list:
    pattern:  /message/list/{page}/
    defaults:
        page: 1
        _controller: SymbbCoreAngularBundle:Angular:index
    options:
      symbb_angular_controller: MessageListCtrl
      symbb_angular_api_route: symbb_api_post_data
      symbb_angular_template:
          route: symbb_template_message_angular
          params:
              file: 'list'

symbb_message_show:
    pattern:  /message/show/{id}/
    defaults: { _controller: SymbbCoreAngularBundle:Angular:index }
    options:
      symbb_angular_controller: MessageShowCtrl
      symbb_angular_api_route: symbb_api_message_data
      symbb_angular_template:
          route: symbb_template_message_angular
          params:
              file: 'show'

symbb_message_new:
    pattern:  /message/new/
    defaults: { _controller: SymbbCoreAngularBundle:Angular:index }
    options:
      symbb_angular_controller: MessageNewCtrl
      symbb_angular_api_route: symbb_api_message_data
      symbb_angular_template:
          route: symbb_template_message_angular
          params:
              file: 'new'

## USER BUNDLE

symbb_user_ucp:
    pattern:  /ucp/
    defaults: { _controller: SymbbCoreAngularBundle:Angular:index }
    options:
      symbb_angular_controller: UcpCtrl
      symbb_angular_template:
        route: symbb_template_ucp_angular
        params:
            file: 'index'

symbb_user_ucp_security:
    pattern:  /ucp/security
    defaults: { _controller: SymbbCoreAngularBundle:Angular:index }
    options:
      symbb_angular_controller: UcpSecurityCtrl
      symbb_angular_template:
        route: symbb_template_ucp_angular
        params:
            file: 'security'