# Routings to get the Templates
symbb_template_default_angular:
    pattern:  /angular/template/default/{file}
    methods:  [GET]
    defaults: { _controller: SymbbTemplateDefaultBundle:Angular:templateFile }

symbb_template_forum_angular:
    pattern:  /angular/template/forum/{file}
    defaults: { _controller: SymbbTemplateDefaultBundle:Angular:forumTemplateFile }

symbb_template_message_angular:
    pattern:  /angular/template/message/{file}
    defaults: { _controller: SymbbCoreMessageBundle:Angular:templateFile }

symbb_template_ucp_angular:
    pattern:  /angular/template/ucp/{file}
    defaults: { _controller: SymbbCoreUserBundle:Angular:ucpTemplateFile }

symbb_template_user_angular:
    pattern:  /angular/template/user/{file}
    defaults: { _controller: SymbbCoreUserBundle:Angular:userTemplateFile }

# AngularJs Controller Routings
# This will create a SF Controller AND a AngularJs Controller automaticly
# and provide the correct content

## FORUM BUNDLE

symbb_forum_search:
    pattern:  /forum/search/{page}/
    defaults:
        page: 1
        _controller: SymbbCoreAngularBundle:Angular:index
    options:
      symbb_angular_controller: ForumSearchCtrl
      symbb_angular_api_route: symbb_api_post_search
      symbb_angular_template:
          route: symbb_template_forum_angular
          params:
              file: 'search'

symbb_forum_topic_show:
    pattern:  /t-{id}-{name}/{page}/
    defaults:
        page: 1
        _controller: SymbbCoreAngularBundle:Angular:index
    options:
      symbb_angular_controller: ForumTopicShowCtrl
      symbb_angular_api_route: symbb_api_topic_data
      symbb_angular_template:
          route: symbb_template_forum_angular
          params:
              file: 'topicShow'

symbb_forum_topic_create:
    pattern:  /f-{forum}/topic/new/
    defaults: { _controller: SymbbCoreAngularBundle:Angular:index }
    options:
      symbb_angular_controller: ForumTopicEditCtrl
      symbb_angular_api_route: symbb_api_topic_data
      symbb_angular_template:
          route: symbb_template_forum_angular
          params:
              file: 'topic'

symbb_forum_topic_edit:
    pattern:  /f-{forum}/topic/{id}/edit
    defaults: { _controller: SymbbCoreAngularBundle:Angular:index }
    options:
      symbb_angular_controller: ForumTopicEditCtrl
      symbb_angular_api_route: symbb_api_topic_data
      symbb_angular_template:
          route: symbb_template_forum_angular
          params:
              file: 'topic'

symbb_forum_post_create:
    pattern:  /t-{topic}/post/new
    defaults: { _controller: SymbbCoreAngularBundle:Angular:index }
    options:
      symbb_angular_controller: ForumPostEditCtrl
      symbb_angular_api_route: symbb_api_post_data
      symbb_angular_template:
          route: symbb_template_forum_angular
          params:
              file: 'post'

symbb_forum_post_edit:
    pattern:  /p-{id}/edit
    defaults: { _controller: SymbbCoreAngularBundle:Angular:index }
    options:
      symbb_angular_controller: ForumPostEditCtrl
      symbb_angular_api_route: symbb_api_post_data
      symbb_angular_template:
          route: symbb_template_forum_angular
          params:
              file: 'post'

symbb_forum_post_quote:
    pattern:  /p-{topic}/quote/{quoteId}
    defaults: { _controller: SymbbCoreAngularBundle:Angular:index }
    options:
      symbb_angular_controller: ForumPostEditCtrl
      symbb_angular_api_route: symbb_api_post_data
      symbb_angular_template:
          route: symbb_template_forum_angular
          params:
              file: 'post'


## MESSAGE BUNDLE

symbb_message_list:
    pattern:  /message/list/{page}/
    defaults:
        page: 1
        _controller: SymbbCoreAngularBundle:Angular:index
    options:
      symbb_angular_controller: MessageListCtrl
      symbb_angular_api_route: symbb_api_post_data
      symbb_angular_template:
          route: symbb_template_message_angular
          params:
              file: 'list'

symbb_message_show:
    pattern:  /message/show/{id}/
    defaults: { _controller: SymbbCoreAngularBundle:Angular:index }
    options:
      symbb_angular_controller: MessageShowCtrl
      symbb_angular_api_route: symbb_api_message_data
      symbb_angular_template:
          route: symbb_template_message_angular
          params:
              file: 'show'

symbb_message_new:
    pattern:  /message/new/
    defaults: { _controller: SymbbCoreAngularBundle:Angular:index }
    options:
      symbb_angular_controller: MessageNewCtrl
      symbb_angular_api_route: symbb_api_message_data
      symbb_angular_template:
          route: symbb_template_message_angular
          params:
              file: 'new'

## USER BUNDLE

symbb_user_ucp:
    pattern:  /ucp/
    defaults: { _controller: SymbbCoreAngularBundle:Angular:index }
    options:
      symbb_angular_controller: UcpCtrl
      symbb_angular_template:
        route: symbb_template_ucp_angular
        params:
            file: 'index'

symbb_user_ucp_security:
    pattern:  /ucp/security
    defaults: { _controller: SymbbCoreAngularBundle:Angular:index }
    options:
      symbb_angular_controller: UcpSecurityCtrl
      symbb_angular_template:
        route: symbb_template_ucp_angular
        params:
            file: 'security'

symbb_userlist:
    pattern:  /users/{page}
    defaults:
      _controller: SymbbCoreAngularBundle:Angular:index
    options:
      symbb_angular_controller: DefaultApiCtrl
      symbb_angular_api_route: symbb_api_userlist
      symbb_angular_template:
        route: symbb_template_default_angular
        params:
            file: 'userlist'

symbb_user_profile:
    pattern:  /user/{id}/{username}
    defaults: { _controller: SymbbCoreAngularBundle:Angular:index }
    options:
      symbb_angular_controller: DefaultApiCtrl
      symbb_angular_api_route: symbb_api_user_data
      symbb_angular_template:
        route: symbb_template_user_angular
        params:
            file: 'profile'