services:
    symbb.core.bbcode.listener.parse:
        class: Symbb\Core\BBCodeBundle\EventListener\ParseListener
        arguments: ['@symbb.core.bbcode.manager']
        tags:
            - { priority: 0, name: kernel.event_listener, event: symbb.core.forum.post.manager.parse.text, method: parsePostText }
            - { priority: 0, name: kernel.event_listener, event: symbb.core.forum.post.manager.clean.text, method: cleanPostText }
            - { priority: 0, name: kernel.event_listener, event: symbb.core.user.parse.signature, method: parseUserSignature }
            - { priority: 0, name: kernel.event_listener, event: symbb.core.message.manager.parse.message, method: parseMessageText }
           
    symbb.core.bbcode.manager:
        class: Symbb\Core\BBCodeBundle\DependencyInjection\BBCodeManager
        arguments: ['@doctrine.orm.symbb_entity_manager', '@symbb.core.site.manager']
        
    symbb.core.bbcode.manager.twig:
        class: Symbb\Core\BBCodeBundle\Twig\BBCodeManagerExtension
        arguments: ['@symbb.core.bbcode.manager', '@jms_serializer']
        tags:
            - { name: twig.extension } 
        
            