symbb_login:
    pattern:  /login
    defaults: { _controller: FOSUserBundle:Security:login }
    
symbb_logout:
    pattern:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout }
    
symbb_login_check:
    pattern:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    
fos_user_security_check:
    pattern:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }
    
symbb_register:
    pattern:  /register
    defaults: { _controller: SymbbFOSUserBundle:Registration:register }
    
symbb_imprint:
    pattern:  /imprint
    defaults: { _controller: SymbbCoreSystemBundle:StaticPage:imprint }
    
symbb_terms:
    pattern:  /terms
    defaults: { _controller: SymbbCoreSystemBundle:StaticPage:terms }

_symbb_core_user:
    resource: "@SymbbCoreUserBundle/Resources/config/routing.yml"
    prefix: /
    
_symbb_core_forum:
    resource: "@SymbbCoreForumBundle/Resources/config/routing.yml"
    prefix: /

_symbb_core_message:
    resource: "@SymbbCoreMessageBundle/Resources/config/routing.yml"
    prefix: /
    
_symbb_core_install:
    resource: "@SymbbCoreInstallBundle/Resources/config/routing.yml"
    prefix: /

_symbb_core_news:
    resource: "@SymbbCoreNewsBundle/Resources/config/routing.yml"
    prefix: /
    
_symbb_core_bbcode_frontend:
    resource: "@SymbbCoreBBCodeBundle/Resources/config/routing/frontend.yml"
    prefix: /