message_list:
    pattern:  /message/list/{page}/
    defaults:
        page: 1
    controller: MessageListCtrl
    api: 
        route: symbb_api_message_list
    template: 
        route: symbb_template_angular_message
        params: 
            file: 'list'
        
message_show:
    pattern:  /message/show/{id}/
    controller: MessageShowCtrl
    api:
        route: symbb_api_message_data
    template: 
        route: symbb_template_angular_message
        params: 
            file: 'show'

message_new:
    pattern:  /message/new/
    controller: MessageNewCtrl
    api:
        route: symbb_api_message_data
    template:
        route: symbb_template_angular_message
        params:
            file: 'new'

message_save:
    api: 
        route: symbb_api_message_save