liip_imagine:
    filter_sets:
        symbb_forum_image: 
            cache: web_path
            quality: 100
            filters:
                strip: ~
                thumbnail: { size: [150, 150], mode: outbound, allow_upscale: true }