
_symbbcoreuserbundle_group_access:
    pattern:  /access/group/{step}
    defaults: { _controller: SymBBCoreUserBundle:AcpAccess:group }
    
    
_symbbcoreuserbundle_group_list:
    pattern:  /group/list
    defaults: { _controller: SymBBCoreUserBundle:AcpGroup:list }
    
_symbbcoreuserbundle_group_new:
    pattern:  /group/new
    defaults: { _controller: SymBBCoreUserBundle:AcpGroup:new }

_symbbcoreuserbundle_group_edit:
    pattern:  /group/{id}/edit
    defaults: { _controller: SymBBCoreUserBundle:AcpGroup:edit }
    
_symbbcoreuserbundle_group_remove:
    pattern:  /group/{id}/remove
    defaults: { _controller: SymBBCoreUserBundle:AcpGroup:remove }
    


_symbbcoreuserbundle_user_list:
    pattern:  /user/list
    defaults: { _controller: SymBBCoreUserBundle:AcpUser:list }

_symbbcoreuserbundle_user_new:
    pattern:  /user/new
    defaults: { _controller: SymBBCoreUserBundle:AcpUser:new}

_symbbcoreuserbundle_user_edit:
    pattern:  /user/{id}/edit
    defaults: { _controller: SymBBCoreUserBundle:AcpUser:edit }

_symbbcoreuserbundle_user_remove:
    pattern:  /user/{id}/remove
    defaults: { _controller: SymBBCoreUserBundle:AcpUser:remove }

_symbbcoreuserbundle_user_enable:
    pattern:  /user/{id}/enable
    defaults: { _controller: SymBBCoreUserBundle:AcpUser:enable }

_symbbcoreuserbundle_user_disable:
    pattern:  /user/{id}/disable
    defaults: { _controller: SymBBCoreUserBundle:AcpUser:disable }
    

_symbbcoreuserbundle_field_list:
    pattern:  /userfield/list
    defaults: { _controller: SymBBCoreUserBundle:AcpField:list }

_symbbcoreuserbundle_field_new:
    pattern:  /userfield/new
    defaults: { _controller: SymBBCoreUserBundle:AcpField:new}
    
_symbbcoreuserbundle_field_edit:
    pattern:  /userfield/{id}/edit
    defaults: { _controller: SymBBCoreUserBundle:AcpField:edit }
    
_symbbcoreuserbundle_field_remove:
    pattern:  /userfield/{id}/remove
    defaults: { _controller: SymBBCoreUserBundle:AcpField:remove }
    
_symbbcoreuserbundle_field_sort:
    pattern:  /userfield/sort
    defaults: { _controller: SymBBCoreUserBundle:AcpField:sort }
    
