user_ucp:
    pattern:  /ucp/
    controller: UcpCtrl
    template: 
        route: symbb_ucp_angular_template
        params: 
            file: 'index'

user_ucp_security:
    pattern:  /ucp/security
    controller: UcpSecurityCtrl
    template:
        route: symbb_ucp_angular_template
        params:
            file: 'security'

user_ucp_data:
    api:
        route: symbb_api_ucp_data

user_ucp_save:
    api: 
        route: symbb_api_user_ucp_save
        
userlist:
    pattern:  /users/{page}
    controller: UserlistCtrl
    api: 
        route: symbb_api_userlist
    template: 
        route: symbb_template_default_angular
        params: 
            file: 'userlist'