user_ucp:
    pattern:  /ucp/
    controller: UcpCtrl
    template: 
        route: symbb_template_ucp_angular
        params: 
            file: 'index'

user_ucp_security:
    pattern:  /ucp/security
    controller: UcpSecurityCtrl
    template:
        route: symbb_template_ucp_angular
        params:
            file: 'security'

user_ucp_data:
    api:
        route: symbb_api_ucp_data

user_ucp_save:
    api: 
        route: symbb_api_user_ucp_save

user_search:
    api:
        route: symbb_api_user_search
        
userlist:
    pattern:  /users/{page}
    controller: UserlistCtrl
    api: 
        route: symbb_api_userlist
    template: 
        route: symbb_template_default_angular
        params: 
            file: 'userlist'

user_profile:
    pattern:  /user/{id}/{username}
    controller: UserProfileCtrl
    api:
        route: symbb_api_user_data
    template:
        route: symbb_template_user_angular
        params:
            file: 'profile'